#########################################
# Exercise 2.9 - Manufacturing Process
# From Deterministic Operations Research by David J. Rader Jr.
# AMPL model by , University of Central Oklahoma
# for MATH 4113/5113 - Operations Research 1 - Fall 2016
#########################################

########################
# SETS                 #
########################

# The set of all products produced
set PRODUCTS;

########################
# PARAMETERS           #
########################

# The revenue generated by selling one ounce of each product (in $ per oz)
param Revenue {PRODUCTS} >= 0;

# The maximum amount of each product that can be sold (in oz)
param MaxDemand {PRODUCTS} >= 0;

# The amount of each product (in oz) that can be made from one pound of raw material
param ProducedFromRaw {PRODUCTS} >= 0;

# The amount (in oz) of product j that can be produced from one ounce of product i
param AmountProduced {PRODUCTS, PRODUCTS} >= 0;

# The cost of converting one ounce of product i into product j
param ConversionCost {PRODUCTS, PRODUCTS} >= 0;

# The labor required to convert one ounce of product i into product j (in man-hours)
param ConversionLabor {PRODUCTS, PRODUCTS} >= 0;

# The cost of raw materials (in $ per lb)
param RawMaterialCost >= 0;

# The amount of time taken to process raw material (in man-hours per lb)
param RawMaterialLabor >= 0;

# The amount of raw material available (in lb)
param RawMaterialAvailable >= 0;

# The amount of labor available (in man-hours)
param LaborAvailable >= 0;

########################
# VARIABLES            #
########################


########################
# OBJECTIVE            #
########################


#########################
# CONSTRAINTS           #
#########################

	
